import type { Href } from 'expo-router';
import type { AppState } from '@/data/store';
import { customerCommitments, eventsFor } from '@/data/selectors';
import type { Channel, Commitment, ID } from '@/data/types';
import { dueLabel, firstName, inr, monthYear, plural, relDay } from './format';

/**
 * Customer Handoff Brief (product feature 7) — the app-side model.
 *
 * Cloud mode gets it from the `handoff-brief` Edge Function (src/data/remote-memory.ts). Demo mode,
 * and cloud mode when the AI is unavailable, builds it here from the store: deterministic, no
 * network, and only from records already on screen — so every line can point at its source.
 */

export type BriefPromise = {
  id: ID;
  title: string;
  dueAt: number;
  status: Commitment['status'];
  promisor: Commitment['promisor'];
  ownerId?: ID;
  sourceEventId?: ID;
  /** Short context: an AI note, or the original words. */
  note?: string;
};

export type HandoffBrief = {
  source: 'ai' | 'local';
  generatedAt: number;
  customerId: ID;
  commitmentId?: ID;
  forMemberId?: ID;
  history: string;
  currentState: string;
  openCommitments: BriefPromise[];
  sensitiveNotes: { text: string; eventIds: ID[] }[];
  nextAction: string;
  evidenceEventIds: ID[];
};

/** Route to the brief sheet (typed routes are generated by the dev server, so this is cast once here). */
export function briefHref(customerId: ID, opts: { commitmentId?: ID; forMemberId?: ID } = {}): Href {
  const params: Record<string, string> = { id: customerId };
  if (opts.commitmentId) params.commitmentId = opts.commitmentId;
  if (opts.forMemberId) params.forMemberId = opts.forMemberId;
  return { pathname: '/customer/[id]/brief', params } as unknown as Href;
}

const CHANNEL_NAME: Record<Channel, string> = {
  whatsapp: 'WhatsApp',
  phone: 'a call',
  email: 'email',
  instagram: 'Instagram',
  manual: 'their usual channel',
  upi: 'their usual channel',
};

/** Words that make a fact worth handling with care (price, complaints, delays, payments). */
const SENSITIVE =
  /\b(price|pricing|discount|expensive|costly|high|budget|complain\w*|unhappy|upset|angry|delay\w*|late|refund|return\w*|damage\w*|broken|issue|problem|dispute|overdue|unpaid|pending payment|careful|sensitive|don[’']?t|never|only)\b/i;

const sentences = (text: string, max: number) =>
  (text.match(/[^.!?]+[.!?]+(\s|$)/g) ?? [text]).slice(0, max).join('').trim();

const lowerFirst = (s: string) => s.charAt(0).toLowerCase() + s.slice(1);

const clip = (s: string, max: number) => (s.length > max ? `${s.slice(0, max - 1).trimEnd()}…` : s);

/** Built on the device from the store. Same inputs → same brief. */
export function buildLocalBrief(
  state: AppState,
  customerId: ID,
  opts: { commitmentId?: ID; forMemberId?: ID; now: number },
): HandoffBrief | null {
  const customer = state.customers.find((c) => c.id === customerId);
  if (!customer) return null;
  const { now } = opts;
  const first = firstName(customer.name);
  const events = eventsFor(state, customer.id);
  const target = opts.commitmentId ? state.commitments.find((c) => c.id === opts.commitmentId && c.customerId === customer.id) : undefined;
  const open = customerCommitments(state, customer.id);
  const promises = (target ? [target, ...open.filter((c) => c.id !== target.id)] : open).slice(0, 10);

  // History: who they are to the business, then the memory summary (or what Nudge has seen).
  const talks = events.filter((e) => e.kind === 'message' || e.kind === 'email' || e.kind === 'call').length;
  const payments = events.filter((e) => e.kind === 'payment').length;
  const since = `${first}${customer.company ? ` (${customer.company})` : ''} has been a customer since ${monthYear(customer.customerSince)}${
    customer.lifetimeValue > 0 ? ` — ${inr(customer.lifetimeValue)} lifetime` : ''
  }.`;
  const seen = talks || payments
    ? `${[talks ? plural(talks, 'conversation') : '', payments ? plural(payments, 'payment') : ''].filter(Boolean).join(' and ')} so far.`
    : 'No conversations recorded yet.';
  const history = [since, customer.summary ? sentences(customer.summary, 2) : seen].join(' ');

  // Right now: the headline, and the last thing the customer said.
  const lastIn = events.find((e) => e.direction === 'in');
  const headline = customer.headline.replace(/[.\s]+$/, '');
  const said = lastIn ? (lastIn.body ? `“${clip(lastIn.body.replace(/\s+/g, ' ').trim(), 90)}”` : lastIn.title.toLowerCase()) : '';
  const currentState = [
    `${headline}.`,
    lastIn ? `${first} last wrote ${relDay(lastIn.at, now)}: ${said}${/[.!?…]”?$/.test(said) ? '' : '.'}` : '',
  ]
    .filter(Boolean)
    .join(' ');

  const openCommitments: BriefPromise[] = promises.map((c) => ({
    id: c.id,
    title: c.title,
    dueAt: c.dueAt,
    status: c.status,
    promisor: c.promisor,
    ownerId: c.ownerId,
    sourceEventId: c.sourceEventId,
    note: c.quote ? `“${clip(c.quote, 80)}”${c.quoteBy ? ` — ${c.quoteBy}` : ''}` : undefined,
  }));

  // Handle with care: sensitive notes first, then durable preferences.
  const facts = state.facts.filter((f) => f.customerId === customer.id && (!f.validUntil || f.validUntil >= now));
  const careful = facts.filter((f) => SENSITIVE.test(f.text));
  const prefs = facts.filter((f) => f.kind === 'preference' && !careful.includes(f));
  const sensitiveNotes = [...careful, ...prefs].slice(0, 4).map((f) => ({ text: f.text, eventIds: f.sourceEventId ? [f.sourceEventId] : [] }));

  // Next best action: the promise this brief is about, else the most urgent one, else a reply / check-in.
  const how = CHANNEL_NAME[customer.preferredChannel];
  const focus = target && target.status === 'open' ? target : promises[0];
  const waiting = state.inbox.find((i) => i.customerId === customer.id && i.bucket === 'needs_reply');
  const nextAction = focus
    ? focus.promisor === 'us'
      ? `${focus.title} — ${lowerFirst(dueLabel(focus.dueAt, now))}. Reach ${first} on ${how}.`
      : `Check in with ${first} on ${how}: ${lowerFirst(focus.title)} (${lowerFirst(dueLabel(focus.dueAt, now))}).`
    : waiting
      ? `Reply to ${first} on ${how}: ${lowerFirst(waiting.what)}.`
      : `Check in with ${first} on ${how}.`;

  const evidence: ID[] = [];
  const add = (id?: ID) => {
    if (id && !evidence.includes(id) && evidence.length < 8 && state.events.some((e) => e.id === id)) evidence.push(id);
  };
  promises.forEach((c) => add(c.sourceEventId));
  sensitiveNotes.forEach((n) => n.eventIds.forEach(add));
  events.slice(0, 2).forEach((e) => add(e.id));

  return {
    source: 'local',
    generatedAt: now,
    customerId: customer.id,
    commitmentId: target?.id,
    forMemberId: opts.forMemberId,
    history,
    currentState,
    openCommitments,
    sensitiveNotes,
    nextAction,
    evidenceEventIds: evidence,
  };
}

/** Plain text for Share / Copy. */
export function briefText(brief: HandoffBrief, state: AppState, now: number): string {
  const customer = state.customers.find((c) => c.id === brief.customerId);
  const name = (id?: ID) => state.members.find((m) => m.id === id)?.name;
  const me = name(state.me);
  const reader = name(brief.forMemberId);
  const lines = [
    `Handoff brief · ${customer?.name ?? 'Customer'}${customer?.company ? ` (${customer.company})` : ''}`,
    [reader ? `For ${firstName(reader)}` : '', me ? `from ${firstName(me)}` : ''].filter(Boolean).join(' · '),
    '',
    'History',
    brief.history,
    '',
    'Right now',
    brief.currentState,
  ];
  if (brief.openCommitments.length) {
    lines.push('', 'Open promises');
    for (const p of brief.openCommitments) {
      const owner = p.promisor === 'customer' ? `${firstName(customer?.name ?? 'Customer')} promised` : name(p.ownerId) ? `owner ${firstName(name(p.ownerId)!)}` : '';
      lines.push(`• ${p.title} — ${lowerFirst(dueLabel(p.dueAt, now))}${owner ? ` (${owner})` : ''}`);
    }
  }
  if (brief.sensitiveNotes.length) {
    lines.push('', 'Handle with care');
    for (const n of brief.sensitiveNotes) lines.push(`• ${n.text}`);
  }
  lines.push('', 'Next best action', brief.nextAction, '', '— from Nudge');
  return lines.filter((l, i) => !(l === '' && lines[i - 1] === '')).join('\n').replace(/^\n+/, '');
}
